# "$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# I like having the path first, them git, then Kubernetes.
format = """
$status\
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$kubernetes\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$shell\
$character"""

[gcloud]
format = '([G](bold blue) ([$project](238)))'

[golang]
format = "([Go](bold 4) [$version](238)) "
version_format = "${major}.${minor}"

[kubernetes]
format = '([☸](bold 33) [($user on )($cluster in )$context (\($namespace\))](238))'
disabled = false

[kubernetes.context_aliases]
"kind-kind" = "kind"
"k3d-.*" = "k3s"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "$var_cluster"

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[status]
disabled = false
symbol = ""
map_symbol = true
format = "[$status $symbol ]($style)"

[git_branch]
disabled = false
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
disabled = false
format = '([$all_status$ahead_behind]($style)) '

[nodejs]
format ="([$symbol](bold green)[$version](238)) "
version_format = "${major}.${minor}"
symbol = " "

[package]
format	= "[$symbol]($style)[$version](238) "
symbol = "pkg "
version_format = "${major}.${minor}"
style = "bold 208"
display_private = false
disabled = false